alphagov/pay-webhooks

.editorconfig
.gitignore
.pre-commit-config.yaml
.secrets.baseline
CONTRIBUTING.md
LICENSE
README.md

Basic repo files that all good repositories have.
See individual commits for details.

PP-8443 Basic repo files

---

pom.xml

Who knows why this works. Who cares

PP-8443 Make mvn verify work

---

pom.xml
src/main/java/uk/gov/pay/webhooks/validations/RequestValidations.java
src/main/java/uk/gov/pay/webhooks/validations/WebhookRequestValidator.java
src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookStatus.java
src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResponse.java
src/test/java/uk/gov/pay/webhooks/validations/WebhookRequestValidatorTest.java
src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookUpdateIT.java

Add json patch endpoint at `PATCH /v1/webhook/{externalId}` which supports replace commands for updating fields.

PP-8496: add PATCH webhook endpoint

---

src/main/java/uk/gov/pay/webhooks/app/WebhooksConfig.java
src/main/java/uk/gov/pay/webhooks/ledger/LedgerService.java
src/main/java/uk/gov/pay/webhooks/ledger/model/Address.java
src/main/java/uk/gov/pay/webhooks/ledger/model/AuthorisationSummary.java
src/main/java/uk/gov/pay/webhooks/ledger/model/CardDetails.java
src/main/java/uk/gov/pay/webhooks/ledger/model/LedgerTransaction.java
src/main/java/uk/gov/pay/webhooks/ledger/model/RefundSummary.java
src/main/java/uk/gov/pay/webhooks/ledger/model/SettlementSummary.java
src/main/java/uk/gov/pay/webhooks/ledger/model/ThreeDSecure.java
src/main/java/uk/gov/pay/webhooks/ledger/model/TransactionState.java
src/main/java/uk/gov/pay/webhooks/message/dao/entity/WebhookMessageEntity.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/webhooks/ledger/LedgerServiceTest.java
src/test/resources/config/test-config.yaml

Ledger client to return transaction by id.
Uses new Http client from standard lib.

PP-8814 Add Ledger client

---

pom.xml
src/main/java/uk/gov/pay/webhooks/app/QueueMessageReceiverConfig.java
src/main/java/uk/gov/pay/webhooks/app/SqsConfig.java
src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
src/main/java/uk/gov/pay/webhooks/app/WebhooksConfig.java
src/main/java/uk/gov/pay/webhooks/queue/EventMessage.java
src/main/java/uk/gov/pay/webhooks/queue/EventMessageDto.java
src/main/java/uk/gov/pay/webhooks/queue/EventMessageHandler.java
src/main/java/uk/gov/pay/webhooks/queue/EventQueue.java
src/main/java/uk/gov/pay/webhooks/queue/InternalEvent.java
src/main/java/uk/gov/pay/webhooks/queue/QueueMessageReceiver.java
src/main/java/uk/gov/pay/webhooks/queue/sqs/QueueException.java
src/main/java/uk/gov/pay/webhooks/queue/sqs/QueueMessage.java
src/main/java/uk/gov/pay/webhooks/queue/sqs/SqsQueueService.java
src/main/java/uk/gov/pay/webhooks/webhook/resource/CreateWebhookRequest.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
src/test/resources/config/test-config.yaml

Read internal events (from elsewhere in the platform) from the SQS queue and process them to send webhook messages.

PP-8986 Read internal events from queue

---

src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueEntity.java
src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessageSendingQueueProcessor.java
src/main/java/uk/gov/pay/webhooks/message/EventMapper.java
src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
src/main/java/uk/gov/pay/webhooks/queue/EventMessage.java
src/main/java/uk/gov/pay/webhooks/queue/EventMessageDto.java
src/main/java/uk/gov/pay/webhooks/queue/EventMessageHandler.java
src/main/java/uk/gov/pay/webhooks/queue/EventQueue.java
src/main/java/uk/gov/pay/webhooks/queue/SNSMessageDto.java
src/main/resources/migrations/0005_create_table_webhook_delivery_queue.sql
src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java

See commit messages for details. Address a number of small issues with the polling/ emitting webhook messages processes.
- add database transaction session for polling
- fix emission database field date granularity
- inject sqs client for guice modules
- parse additional SNS/ SQS message layers

PP-9001 Patch Webhook send process

---

.github/workflows/push-to-main.yml

PP-9107 Fix release tag extraction

---

src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java

If there's a resource type we don't currently have an API representation of, filter it out rather than returning the Ledger Transaction model

PP-9113: Filter out unsupported resource types

---

src/main/resources/migrations/0007_add_index_webhooks_to_send.sql

Add index as ﻿this column is used frequently to poll for the next available message to send

PP-9201: Add index on webhook delivery status

---

src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueDao.java
src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessageSendingQueueProcessor.java
src/test/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueDaoTest.java
src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempterTest.java

Add metric counter for delivery results, this will be useful in monitoring the levels of failed delivery.

PP-9201: Add metric counter for delivery results

---

pom.xml

Reverts alphagov/pay-webhooks#207
This did not seem to work.

Revert "Bump dropwizard-bom from 2.0.29 to 2.1.0"

---

src/main/resources/migrations/0009_alter_table_webhook_delivery_queue_add_column_duration_in_millis.sql

Add an integer column to track response time from webhook delivery queue
message attempts.

PP-9201 Database migration to record webhook message response time

---

src/main/java/uk/gov/pay/webhooks/queue/EventMessageHandler.java
src/main/java/uk/gov/pay/webhooks/queue/QueueMessageReceiver.java

The current solution for ensuring a valid db transaction context is to
use hibernate `internal` methods to open and bind a session manually.
This is required because dropwizard managed `UnitOrWork` contexts are
only available within Jersey resources by default.
Use the unit of work aware proxy factory to build a polling service that
is wrapped in the dropwizard hibernate managed context and can make use
of the standard `@UnitOfWork` annotations.
This refactor follows a pattern set in
https://github.com/alphagov/pay-webhooks/pull/251

BAU Replace internal hibernate code

---

.github/workflows/pr.yml
.github/workflows/push-to-main.yml
pom.xml
src/test/java/uk/gov/pay/webhooks/ledger/pact/LedgerServiceConsumerTest.java
src/test/resources/pacts/webhooks-ledger-get-payment-transaction.json

- added consumer pact for ledger
- added maven plugin for pact provision + supporting deps
- updated github actions to publish and run pact tests

PP-9829 ledger consumer pact test

---

.github/workflows/post-merge.yml
.github/workflows/run-tests.yml

- enable manual trigger of main branch workflow
- rename workflows to be inline with other pay repos

PP-9829 tidy up GHA workflows

---

pom.xml

Use the latest Pact JVM consumer/provider dependencies

PP-9829 use latest pact provider/consumer

---

src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java

The A/C for agreed logging were updated and missed by this change
request. Update the log to match expected monitoring.
Vaguely relates to https://github.com/alphagov/pay-webhooks/pull/391

PP-9016 Bring logging in line with monitoring

---

.github/workflows/run-tests.yml
README.md
openapi/webhooks_spec.yaml

Add a check in the GitHub actions workflow that runs on PR builds to check whether there are uncommitted changes after running `mvn compile`. If there are, this suggests that there have been changes to the API specification and the OpenApi file has not been regenerated. Fail the build when uncommitted changes are detected.
Add API Specification section to README

PP-10255 Check if there are uncommitted changes to OpenApi file

---

Dockerfile

Upgrade the Docker base image to Java 17.0.5.

PP-10363 Upgrade to Java 17.0.5

---

src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessagePollingService.java

Currently if the webhook delivery queue DAO `nextToSend` fails to connect to the database, an exception will be raised that won't be handled by the polling wrapper code. This will cause the scheduled executor service the code is running in to stop and it has no way to recover other than an app restart.
In any other code we have the runs managed background tasks, there's generally a top level exception handler to log when something has gone completely wrong (i.e couldn't access a database during an short upgrade window) and allow the thread to continue safely.
Add the exception handling in the main `sendIfAvailable` wrapper as this is where we can most clearly clean up the MDC logging contexts, none of the thread code that runs outside of this should be able to raise exceptions. This …

PP-10191 Handle unknown exceptions on the message to send polling thread

---

src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java

https://github.com/alphagov/pay-webhooks/pull/626 was incorrect in that it was logging the full webhook url instead of the
[domain](https://github.com/alphagov/pay-webhooks/blob/main/src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java#L77).

PP-10631: Log domain instead of URL

---

pom.xml

Reverts alphagov/pay-webhooks#671

Revert "Bump dropwizard-bom from 2.1.4 to 2.1.5"

---

pom.xml

Reverts alphagov/pay-webhooks#760

Revert "Bump dropwizard-bom from 2.1.4 to 2.1.6"

---

.github/workflows/post-merge.yml

PP-11292 update pact broker host

---

Dockerfile
pom.xml
src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
src/main/java/uk/gov/pay/webhooks/app/WebhooksConfig.java
src/main/resources/config/config.yaml
src/test/resources/config/test-config.yaml

Set up a prometheus metric endpoint /metrics.
Append ECS metadata info (via the PrometheusDefaultLabelSampleBuilder class in pay-java-commons) as default labels.

PP-11223: Set up prometheus metrics

---

pom.xml

PP-11652 Upgrade from WireMock 2.35.1 to 3.2.0

---

src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java

PP-11652 Fix logging to Sentry

---

src/main/resources/config/config.yaml

PP-11652 fix sentry logging type

---

src/test/java/uk/gov/pay/rule/PostgresTestDocker.java

Bump Postgres test container to 15.2, like we have in real envs.

PP-11895-upgrade-postgres-container

---

src/main/resources/config/config.yaml

Bind to 127.0.0.1 by default instead of 0.0.0.0
I followed the exact same testing strategy as https://github.com/alphagov/pay-connector/pull/5539 and achieved the same results

PP-13145: Accept BIND_HOST env var and default to localhost

---

pom.xml

Fine tune Dropwizard 4 bom dependencies.

PP-13658 refine Dropwizard 4 migration
