- .secrets.baseline
- pom.xml
- src/main/java/uk/gov/pay/webhooks/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/WebhooksConfiguration.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksConfig.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/healthcheck/HealthCheckResource.java
- src/main/resources/migrations.xml
- src/main/resources/migrations/0001_create_table_webhooks.sql
- src/test/java/uk/gov/pay/extension/AppWithPostgresExtension.java
- src/test/java/uk/gov/pay/rule/PostgresTestDocker.java
- src/test/java/uk/gov/pay/webhooks/healthcheck/HealthCheckResourceIT.java
- src/test/resources/config/test-config.yaml
Adds dependencies required to setup, configure and run migrations on a Postgres database: 
* dropwizard core migrations
* postgres driver
Sets up dependency injection in line with other apps (using Guice) to set the standard and clean up existing healthcheck endpoint. 
Adds first database migration to setup a simple table.
Adds standard commons database healtcheck with assertion on healthy database connection.
Sets up test environment to run tests against an actual database
* JUnit5
* testcontainers
* hamcreset matchers
* reset assured
> PP-8443 Configure database setup

- .github/workflows/run-tests.yml
Depends on https://github.com/alphagov/pay-webhooks/pull/4
Use JDK 17 as specified in the pom file.
Run on standard Ubuntu base, similar to unit tests run by other repos.
Output of action should be the result of `mvn clean integration-test`.
> BAU GitHub Action for integration tests

- pom.xml
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookDTO.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookResource.java
- src/main/java/uk/gov/pay/webhooks/webhook/entity/WebhookEntity.java
- src/main/java/uk/gov/pay/webhooks/webhook/entity/WebhookStatus.java
- src/main/java/uk/gov/pay/webhooks/webhook/entity/dao/WebhookDao.java
- src/main/resources/migrations/0001_create_table_webhooks.sql
- src/test/java/uk/gov/pay/webhooks/healthcheck/HealthCheckResourceIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookResourceIT.java
- src/test/resources/config/test-config.yaml
Dropwizard default JPA implementation is Hibernate.
We were having problems using EL with Java 17 in Dropwizard. Hibernate works quite straightforwardly - `WebhookResourceIT` is a passing test using new Hibernate things.
with @mrlumbu, @sfount
> PP-8443 Switch from EclipseLink to Hibernate

- pom.xml
- src/main/java/uk/gov/pay/webhooks/webhook/CreateWebhookRequest.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookResource.java
- src/main/java/uk/gov/pay/webhooks/webhook/entity/WebhookEntity.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookResourceTest.java
Rename generic DTO to describe it as the serialiser for creating webhook
requests.
Build webhook entities from the create webhook request.
Add Jackson/ Javax annotations to the serialiser and resource to ensure
the required values are set, and are within correct constraints.
Unit test the resource layer for validations.
> PP-8443 Add Jackson validation to webhook resource

- Dockerfile
- config.yml
- dependabot.yaml
- docker-startup.sh
- src/main/resources/config/config.yaml
Dockerfile added same as other java apps.
Have used standard docker startup script, but commented out
wait on dependencies bit until we have some dependencies.
Moved config to the right place so that it is included
in target.
Added dependabot file to keep base image up to date.
```
mvn clean package
docker build . -t webhooks
docker run -e JAVA_OPTS='-Xms128m -Xmx1G' -it webhooks
```
> PP-8475 Dockerfile

- pom.xml
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/eventtype/EventTypeName.java
- src/main/java/uk/gov/pay/webhooks/eventtype/dao/EventTypeDao.java
- src/main/java/uk/gov/pay/webhooks/eventtype/dao/EventTypeEntity.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
- src/main/resources/migrations/0002_create_table_event_types.sql
- src/main/resources/migrations/0003_create_table_webhook_subscriptions.sql
- src/test/java/uk/gov/pay/webhooks/webhook/dao/WebhookDaoTest.java
Adds migrations and JPA things for event subscriptions.
As agreed we will use a join table to map webhooks to event
types. Ihave modelled inJPA as one to many because I don't think
we will ever care about tracing back from one event type
to see all the webhooks subscribed.
The migration includes the creation of a single event type
(card_payment_captured). This is largely to get things off
the ground and am happy to rename etc.
I have used an enum to model the name of the event type,
and then used some slightly fancy @transient logic to
automatically go from Enum to string and back. This means
we can use nice type safe enum through the business logic
and have it serialised to db correctly.
I have used a Dropwixard DAO test to test persistence layer
logic. I will add full integration test …
> PP-8443 add subscription persistence

- src/main/java/uk/gov/pay/webhooks/eventtype/EventTypeName.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/CreateWebhookRequest.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResponse.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceTest.java
Adds functionality to set webhook subscriptions on
webhook creation, and retrieve subscriptions as part of
webhook.
I have used a webhook service to encapsulate the small
amount of business logic needed to deal with subscriptions.
There is probably more to do on validation, but using
an enum for event type names gets us a lot of the way
there.
> PP-8443 add subscriptions to webhook resource

- src/main/resources/migrations/0004_create_table_webhook_messages.sql
A webhook message is a representation of what we will actually send to a service that has a webhook configured with a subscription to a particular event, combining data from the event itself and the transaction to which the event relates.
> PP-8814 Database migration to add webhooks_messages table

- pom.xml
- Explicitly depend on `jackson-core`, `jackson-annotations` and `jackson-databind` because Dropwizard depends on older versions of these so if we do not explicitly depend on all of them we end up with a confusing version mix
- Use bills of materials (BOMs) to avoid having to mention version numbers every time
- Update everything to the latest and greatest
- Reorder dependencies to be more logical
> PP-8814 Update dependencies in POM

- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/message/EventMapper.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDao.java
- src/main/java/uk/gov/pay/webhooks/message/dao/entity/WebhookMessageEntity.java
- src/main/java/uk/gov/pay/webhooks/queue/InternalEvent.java
- src/main/java/uk/gov/pay/webhooks/util/ExternalIdGenerator.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/WebhookDao.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
- src/main/resources/migrations/0004_create_table_webhook_messages.sql
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
Adds webhook message service with method `handleInternalEvent`
that will be used to process incoming internal events.
At the moment the method finds webhooks subscribed to
the event, and then for each such webhook builds a webhook
message (including fetching transaction from ledger),
and stores it.
I have added a test for the filtering, but will leave off
writing an integration test until we have this working end
to end.
> PP-8814 Filter internal events and build webhook message

- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/util/IdGenerator.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/SigningKeyResponse.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
- src/main/resources/migrations/0001_create_table_webhooks.sql
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookSigningKeyIT.java
Sets a signing key when a Webhook is created
Provides get endpoint to retrieve signing key at: `GET /{externalId}/signing-key`
Provides post endpoint to reset signing key at: `POST /{externalId}/signing-key`
Note: As this changes an existing migration you will need to nuke your database to test locally.
> PP-8849: provision signing key

- pom.xml
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageSender.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageSignatureGenerator.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageSenderTest.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageSignatureGeneratorTest.java
Not-yet-hooked-up-to-anything code to send a webhook message to the configured callback URL. The request includes an HTTP header of the following form:
```
Pay-Signature: <SHA-256 HMAC of body using configured secret>
```
The expected signature in `WebhookMessageSignatureGenerator` has been verified using two online HMAC generators.
`WebhookMessageSender` just concerns itself with sending the webhook. The response (which may have an HTTP status code indicating an error) is returned to the caller and exceptions are allowed to propagate. The future calling code will do something sensible to handle any errors.
> PP-8813 Send webhook message with signature header

- pom.xml
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueEntity.java
- src/main/java/uk/gov/pay/webhooks/message/dao/entity/WebhookMessageEntity.java
- src/main/resources/migrations/0005_create_table_webhook_delivery_queue.sql
This splits out the new entity for the webhook delivery queue, so we can start building views for it, separate from the sending functionality.
> PP-9001: webhook delivery queue entity

- Dockerfile
Use an official Eclipse Temurin Docker base image that provides a Java 17.0.1 JDK running on Alpine Linux.
The previous image is no longer being updated and provides an early access Java 17 JDK running on Alpine Linux.
> BAU — Use Alpine Linux Eclipse Temurin Java 17.0.1 Docker base image

- src/test/java/uk/gov/pay/extension/AppWithPostgresAndSqsExtension.java
- src/test/java/uk/gov/pay/rule/SqsTestDocker.java
- src/test/java/uk/gov/pay/webhooks/healthcheck/HealthCheckResourceIT.java
- src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookListIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookSigningKeyIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookUpdateIT.java
This adds an integration test (and associated test harness based on that in Ledger) for the SQS receiving functionality added in #31 
It is anticipated we can also use this functionality in future as part of a more complete end-to-end webhooks integration test.
> PP-8986: Add integration test for receiving SQS message

- pom.xml
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/resources/config/config.yaml
The lambda responsible for ingesting output from fargate instances
requires an `environment` attribute to be set (using commons structured
logging). This sets the `environment` and `container` attributes for all
messages logged by the service which will allow these lines to be
ingested.
> BAU Allow webhooks logs to go through to Splunk

- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessageSendingQueueProcessor.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempterTest.java
Extracts the sending & retry logic from the scheduled task execution to make it more test-able.
* Extract attempt sending logic in separate SendAttempter class
* Prettify delivery result message with HTTP reason
* Inject WebhookMessageSender into SendAttempter to allow for mocking in tests
* Add tests for SendAttempter
> PP-9001: Extract attempt sending logic in separate SendAttempter class

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueDao.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueEntity.java
- src/main/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDao.java
- src/main/java/uk/gov/pay/webhooks/message/dao/entity/WebhookMessageEntity.java
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookDeliveryQueueResponse.java
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookMessageResponse.java
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookMessageSearchResponse.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
- src/test/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDaoTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
Adds endpoints for interrogating webhook messages and their delivery attempts.
---
`/v1/webhook/{externalId}/message`
List the messages for a given webhook
- ordered by created date
- 10 per page
`?page` - optional, specify how far into the data to fetch messages
`?status` - optional, filter by a given status `"SUCCESSFUL"`, `"FAILED"`
---
`/v1/webhook/{externalId}/message/{messageId}`
Get details for a given webhook and message
---
`/v1/webhook/{externalId}/message/{messageId}/attempt`
List all delivery attempts for a given webhook and message
> PP-8557 Webhook messages endpoint

- src/main/java/uk/gov/pay/webhooks/eventtype/EventTypeName.java
- src/main/java/uk/gov/pay/webhooks/message/EventMapper.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessage.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessageDto.java
- src/main/java/uk/gov/pay/webhooks/queue/InternalEvent.java
- src/main/resources/migrations/0002_create_table_event_types.sql
- src/test/java/uk/gov/pay/webhooks/validations/WebhookRequestValidatorTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
Add entries for
* Payment started
* Payment succeeded
* Payment refunded
Clean up duplication in K/V maps.
Add an additional case to fetch a parent resource if the event relates to a
dependant resource.
> PP-9077 Support all initially proposed payment event types

- .github/workflows/push-to-main.yml
Once we have run tests on main, tag release by incrementing
previous release by one. This script is a gutted version of
https://github.com/alphagov/pay-dockerfiles/blob/main/.github/workflows/build-carbon-relay-image.yml#L62-L88
See it working (except actually applying tag) here
https://github.com/alphagov/pay-webhooks/runs/4883782227?check_suite_focus=true
> PP-9107 Tag on main merge

- .github/workflows/push-to-main.yml
Need `contents: write` to write the tag. Have restricted this to the one job that needs it, which is run after merge.
> PP-9107 Fix workflow permissions

- src/main/java/uk/gov/pay/webhooks/ledger/model/SettlementSummary.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/message/apirepresentation/RefundApiRepresentation.java
- src/test/java/uk/gov/pay/webhooks/message/apirepresentation/RefundApiRepresentationTest.java
Adds refund representation, similar to that returned by Public API, except the `_links` block is removed and instead `payment_id` is used to refer to the parent transaction.
> PP-9113: Add refund resource representation

- Dockerfile
Also switch from a JDK image to a JRE image, which should be smaller while still meeting our needs.
> BAU — Upgrade Eclipse Temurin Java runtime from 17.0.1 to 17.0.2

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueDao.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueEntity.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessageSendingQueueProcessor.java
- src/main/java/uk/gov/pay/webhooks/ledger/model/SettlementSummary.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageBody.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/message/dao/entity/WebhookMessageEntity.java
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookDeliveryQueueResponse.java
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookMessageResponse.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResponse.java
- src/main/resources/migrations/0006_alter_table_webhooks_alter_column_created_date_type_timestamp_with_time_zone.sql
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueDaoTest.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempterTest.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageBodyTest.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageSenderTest.java
- src/test/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDaoTest.java
- src/test/java/uk/gov/pay/webhooks/util/InstantDeserializerTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/dao/WebhookDaoTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceTest.java
In short, make the following so:
- Except in entity classes, all timestamps in the application are `Instant`s
- In entity classes (that is, classes that represent something in the database), all timestamps are `OffsetDateTime`s
- In the database, all columns holding timestamps are of the type `TIMESTAMP WITH TIME ZONE`
Longer explanation:
Up until now, the webhooks application used a mixture of `Instant`s, `Date`s and `ZonedDateTime`s to represent timestamps. In the database, timestamps were a mixture of `TIMESTAMP WITH TIME ZONE` and `TIMESTAMP WITHOUT TIME ZONE`.
`Instant` is clearly the best class to model timestamps in the application. While we used Instants in most places, in entity objects we used `Dat`e because Hibernate can natively persist this to the database. `Date` is …
> PP-9202 Improve how we model timestamps

- src/main/java/uk/gov/pay/webhooks/message/apirepresentation/PaymentApiRepresentation.java
- src/test/java/uk/gov/pay/webhooks/message/apirepresentation/PaymentApiRepresentationTest.java
We are seeing an exception on Webhooks in Test:
```
uk.gov.pay.webhooks.ledger.model.AuthorisationSummary.getThreeDSecure()" because the return value of "uk.gov.pay.webhooks.ledger.model.LedgerTransaction.getAuthorisationSummary() is null" 
```
which suggests this field is not always present in the ledger payload. This PR makes it optional, so no NPE will be thrown if it is not present.
> BAU: reflect that authorisation summary is optional in ledger payload

- pom.xml
Mockito now publish a bill of materials so use that in our POM.
We currently only use one Mockito dependency so this does not make any real difference but it’s nice to have in case we add more in the future.
> BAU — Dependency configuration: use Mockito bill of materials

- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookMessageResponse.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
The admin tool currently parses the `resource` attribute of the webhook
message to get the transaction id (to be linked to and referenced). This
shouldn't be relied on as the shape of the api may in the future be
configurable.
The WebhookMessageEntity already parses and stores the resource ID based
on internal pay messages. Expose this on the serialised record so that
it can be used by the admin tool consumer.
> BAU Serialise resource id and type on webhook message

- src/main/java/uk/gov/pay/webhooks/queue/EventMessage.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessageDto.java
- src/main/java/uk/gov/pay/webhooks/queue/InternalEvent.java
- src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
Remove reference (pseudo contracts) to data we don't need on events.
Content of events isn't used when processing webhooks so reflect that
with models.
> BAU Remove unused serialised event fields

- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessage.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessageDto.java
- src/main/java/uk/gov/pay/webhooks/queue/InternalEvent.java
- src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java
The standard event definition (currently specified by Connector) sends
events with a top level `timestamp` attribute. For some reason this was
transformed by the event store (currently Ledger) into `event_date`.
This has been undone to avoid confusion between service publisher/
consumer contracts.
Update parsing to reflect was webhooks should expect from the SNS/SQS
events stream.
Relates to https://github.com/alphagov/pay-webhooks/pull/140
> BAU Use original producer naming for parsing events

- Dockerfile
Upgrade the base Docker image from `eclipse-temurin:17.0.2_8-jre-alpine` to `eclipse-temurin:17.0.3_7-jre-alpine`.
> BAU — Upgrade from Java 17.0.2 to Java 17.0.3

- .github/workflows/pr.yml
- .github/workflows/push-to-main.yml
- checkout from v2 (`pr.yml`) and v2.3.4 (`push-to-main.yml`) to v3.0.2
- setup-java from v2 to v3.2.0
- cache from v2 to v3.0.2
- upload-artifact from v2 to v3.0.0
In all cases, the main change is that the Action now runs using Node.js 16 rather than Node.js 12.
In line with our policy on GitHub Actions, consistently pin each Action to its release commit SHA rather than a version number (previously, only checkout in `push-to-main.yml` did this, being pinned to `5a4ac90`, which is v2.3.4).
> BAU — Upgrade GitHub-provided GitHub Actions to latest versions

- .github/workflows/push-to-main.yml
See ADR: https://github.com/alphagov/pay-architecture/pull/49/files
This means that for PRs where the only changes are files in the `.github` folder, merging will not trigger the post-merge workflow (release and tag) or subsequent Concourse builds.
> BAU: Exclude Github Actions/Dependabot from post-merge workflow

- src/main/resources/migrations/0008_index_searched_columns.sql
Use the queries defined in the entities to cover attributes used in gets
and searches with indexes.
- `WebhookEntity`
- `WebhookMessageEntity`
- `WebhookDeliveryQueueEntity`
Also include a unique index constraint on the subscription table to both
speed up the many to one join and to avoid code mistakenly subscribing a
webhook to any given event hook more than once.
> BAU Add basic indexes on webhook tables

- src/main/resources/migrations/0008_index_searched_columns.sql
If liquibase picks up an sql file with no comments it will create a
default change set (in this example
`changeset:0008_index_searched_columns.sql`).
If there is a liquibase comment but no explicit `changeset` comment it
looks like the file is not run by liquibase as it doesn't apply the
default behaviour.
Remove comments to use the default liquibase changeset and rollback
behaviour for this change.
> BAU Fix invalid liquibase file

- pom.xml
Reverts alphagov/pay-webhooks#218
This did not seem to work.
> Revert "Bump dropwizard-sentry from 2.0.29 to 2.1.0"

- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksKeys.java
- src/main/java/uk/gov/pay/webhooks/app/filters/LoggingMDCRequestFilter.java
- src/main/java/uk/gov/pay/webhooks/app/filters/LoggingMDCResponseFilter.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessagePollingService.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessageHandler.java
- src/main/java/uk/gov/pay/webhooks/queue/QueueMessageReceiver.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
For consistency with other apps, add the commons `LoggingFilter` for
structured request logs.
Add a custom request filter to take webhook context specific vars from
the path and query params and provide them to all subsequent logs.
Add structured logs to the two main webhook processes 
* recording messages to be sent by consuming the event stream
* sending webhook messages
----
Refactor code for sending messages to have a single method to handle
responses. This allows us to uniformly add a structured log that will be
easy to grep/ process in Splunk.
---
Tests should still pass.
> BAU Improve logging 

- src/main/java/uk/gov/pay/webhooks/app/WebhooksKeys.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
When a webhook message attempts to deliver, we record metadata about the
request in the log stream in order to pivot queries and dashboards
around different stats.
Also include the "reason" for the response, the logic for this is
already considered by the send attempter method and includes reasons for
results that don't have a HTTP status code (auto derived if there is a
HTTP status code available).
> BAU Include attempt response reason in log stream

- src/main/java/uk/gov/pay/webhooks/app/WebhooksKeys.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessageDto.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessageHandler.java
- src/main/java/uk/gov/pay/webhooks/queue/EventQueue.java
- src/main/java/uk/gov/pay/webhooks/queue/InternalEvent.java
- src/test/java/uk/gov/pay/webhooks/queue/EventQueueTest.java
The deployed event message handler is failing to process some messages
emitted by connector that are missing service id and live properties.
This could eventually be a pact contract requirement for system events
however for now the process should be able to manage this case (in
favour of NPE).
Check for these properties before using them to check for webhook
subscriptions with the DAO.
Add coverage to check that events missing these properties are filtered
out before being handed to the webhook message processing code.
Change the event handling rescheduling log from an error to a warn, this
error should be on events eventually making their way to the dead letter
queue.
> BAU Filter out events that don't contain service id or live properties

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessagePollingService.java
After a configured `nextRetryIn` count webhook messages will no longer be attempted to a given webhook. When this happens log a warning tracking this.
> BAU Log entry when webhook message can't be delivered

- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksConfig.java
- src/main/java/uk/gov/pay/webhooks/validations/CallbackUrlDomainNotOnAllowListException.java
- src/main/java/uk/gov/pay/webhooks/validations/CallbackUrlMalformedException.java
- src/main/java/uk/gov/pay/webhooks/validations/CallbackUrlProtocolNotSupported.java
- src/main/java/uk/gov/pay/webhooks/validations/CallbackUrlService.java
- src/main/java/uk/gov/pay/webhooks/validations/WebhookRequestValidator.java
- src/main/java/uk/gov/pay/webhooks/webhook/exception/ErrorResponse.java
- src/main/java/uk/gov/pay/webhooks/webhook/exception/ValidationExceptionMapper.java
- src/main/java/uk/gov/pay/webhooks/webhook/exception/WebhookExceptionMapper.java
- src/main/java/uk/gov/pay/webhooks/webhook/exception/WebhooksErrorIdentifier.java
- src/main/java/uk/gov/pay/webhooks/webhook/exception/WebhooksException.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
- src/test/java/uk/gov/pay/webhooks/validations/CallbackUrlServiceTest.java
- src/test/java/uk/gov/pay/webhooks/validations/WebhookRequestValidatorTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookListIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookSigningKeyIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookUpdateIT.java
- src/test/resources/config/test-config.yaml
Follows on from https://github.com/alphagov/pay-webhooks/pull/362
Include a call to the the callback url service on the create and update
webhook resource to ensure the url is validated whenever a webhook is
mutated. This requires passing down the live context for any given
webhook resource.
There's a remaining developer note to demonstrate that we could move the
create webhook validation to a custom constraint validator to bring it
inline with other basic validation done for create requests. Currently
this is entirely separate from the validation done against the json
patch logic (which is something else that could be improved in the
future).
For now this will throw separate and one off exceptions for the callback
url on the update endpoint, rather than throwing a `ValidationException` …
> PP-9016 Hook callback URL validation into create and update

- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueEntity.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageSender.java
- src/main/java/uk/gov/pay/webhooks/validations/CallbackUrlDomainNotOnAllowListException.java
- src/main/java/uk/gov/pay/webhooks/validations/CallbackUrlService.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempterTest.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageSenderTest.java
Adds `WONT_SEND` status for message delivery attempts.
For live messages only, validates that the callback url being delivered
to at the time is in the allow list.
Adds logging expected by ticket for tying into protective monitoring.
> PP-9016 Check allow list at point of sending a message

- src/main/resources/migrations/0010_alter_table_webhook_delivery_queue_alter_check_status_constraint.sql
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/WebhookDeliveryQueueIT.java
Add `WILL_NOT_SEND` to postgres status values check. Exactly what this
constraint protects against should be reviewed in a subsequent change.
For the meantime, add a parameterised assertion that ensures that for any given
delivery status enum can be persisted in the real database.
> PP-9016 Extend delivery status postgres check for WILL_NOT_SEND

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/WebhookNotActiveException.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageSender.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempterTest.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageSenderTest.java
If a webhook has been moved into the `INACTIVE` or `DISABLED` states it
should not attempt to send webhook messages.
Check the webhook status when actually sending the message to ensure
there are no edge cases allowing messages through.
> PP-9865 Don't send or enqueue messages for non-active webhooks

- src/main/resources/migrations/0011_add_event_types_failed_expired.sql
Include entries for "a payment fails" and "a payment expires".
> PP-9274 Add new webhook subscription event types database

- src/main/java/uk/gov/pay/webhooks/eventtype/EventTypeName.java
- src/main/java/uk/gov/pay/webhooks/message/EventMapper.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/test/java/uk/gov/pay/webhooks/validations/WebhookRequestValidatorTest.java
Depends on https://github.com/alphagov/pay-webhooks/pull/386
Introduces new failed and expired mappings to internal events.
Update successful event mappings, previous "authorisation success" had
been used however this event is reached before a paying user "confirms"
a payment and the payment can still be cancelled at this point in time.
Instead of this use the confirmed for capture event which will guarantee
that the payment will be taken.
> PP-9274 Update internal hooks for subscriptions

- src/main/java/uk/gov/pay/webhooks/validations/CallbackUrlService.java
We have a [saved Splunk search](https://github.com/alphagov/cyber-security-splunk-apps/blob/master/gds-004-pay/default/savedsearches.conf#L1207) for webhooks, triggered by occurrences of a log message. 
Splunk search: `Cannot set domains not found in the allow list`
Webhooks log: `Cannot set domains not found in allow list`
It's easier to change the webhooks message than the Splunk search, hence this PR to add the missing `the`.
> PP-9016: Fix typo in error message to match Splunk search

- src/main/resources/config/config.yaml
Hibernate seems to be generating and logging statistics for every single
database connection, by default.
How this behaviour was introduced or is on by default isn't clear at
this stage, however with production volumes the logs generated are
problematic.
Disable these logs by setting the hibernate property and investigate
why this behaviour is enabled in the first place.
Relates to https://github.com/alphagov/pay-webhooks/pull/373
> BAU Disable hibernate statistics logs

- src/main/java/uk/gov/pay/webhooks/app/QueueMessageReceiverConfig.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageSender.java
- src/main/resources/config/config.yaml
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempterTest.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessagePollingServiceTest.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageSenderTest.java
- src/test/resources/config/test-config.yaml
The apache client gives us more control over:
- connection pool behaviour, specifically around timeout behaviours for
connection pools where we have no control over the receiving servers
connection behaviour. We suspect these connection pools being
terminated result in intermittent "Connection Reset" errors
- ease of specifying TLS and cipher requirements
> PP-9016 Compare apache and java net http client

- src/main/java/uk/gov/pay/webhooks/app/QueueMessageReceiverConfig.java
- src/main/java/uk/gov/pay/webhooks/app/WebhookMessageSendingQueueProcessorConfig.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/test/resources/config/test-config.yaml
The configuration properties for message sending client timeouts were
applied to the wrong configuration file.
This passed tests because the `test-config.yaml` correctly (incorrectly)
set the configuration on the incorrect property.
The real configuration file `config.yaml` incorrectly (correctly) set
the configuration on the right property however this couldn't be parsed
by the app causing it not to start.
> PP-9016 Fix webhook sender timeout config

- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageBody.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageBodyTest.java
Rename `resource_type_name` (internal) to `resource_type` (as specified in the docs).
Use `${entity_type}_id` identifier format as consistent with our Pay API resources. This could be changed in the future but should be done all at once with backwards compatability in mind.
> BAU Line webhook message body fields up with docs

- src/test/java/uk/gov/pay/extension/AppWithPostgresAndSqsExtension.java
- src/test/java/uk/gov/pay/rule/PostgresTestDocker.java
- src/test/java/uk/gov/pay/rule/SqsTestDocker.java
- src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java
- baselining on architecture agnostic `postgres:11.16`
- replaced generic test container with postgres module
- the module exposes the relevant port and can automatically determine when the database is healthy, removing the need to sleep the thread
- updated local sqs image to be consistent with other Pay applications
- removed some unused methods in test helpers
- added message body to example message in EventQueueIT receive test, fixes AmazonSQSException
> PP-10004 M1 support for integration tests

- src/main/resources/config/config.yaml
- src/test/resources/config/test-config.yaml
dropwizard's own connection pool fails to reconnect when the db is restarted. 
- Enable the periodic validation of idle connections. This will ensure that in case the connection to the DB is reset, the connection pool is re-connecting to the db.
> PP-10191 change connection pool reconnect settings

- openapi/webhooks_spec.yaml
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/healthcheck/HealthCheckResource.java
- src/main/java/uk/gov/pay/webhooks/healthcheck/SQSHealthCheck.java
- src/test/java/uk/gov/pay/extension/AppWithPostgresAndSqsExtension.java
- src/test/java/uk/gov/pay/rule/PostgresTestDocker.java
- src/test/java/uk/gov/pay/webhooks/healthcheck/HealthCheckResourceIT.java
AWS healtcheck does not take HealthCheck.Result into consideration when calling the endpoint.
- refactor resource to return `503` when at least one of the healthcheck result is is not healthy.
- implement sqs queue check (we don't check for it at the momemnt)
> PP-10191 refactor healthcheck

- .github/workflows/post-merge.yml
- .github/workflows/run-tests.yml
Reverts alphagov/pay-webhooks#565
There are two commits with different SHAs, both tagged as 3.2.0. For whatever reason Git chooses the SHA of the older commit. Reverting to 3.1.0 until issue is solved.
> Revert "Bump actions/checkout from 3.1.0 to 3.2.0"

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueEntity.java
The webhook delivery queue DAO exposes a method to search for webhook messages which are in a pending state and are now scheduled to be sent.
There are a number of individual indexes on the delivery queue table:
- `send_at`
- `created_at`
- `delivery_status`
Both `send_at` and `delivery_status` are used in the query, which should correctly use index scans to immediately return the value.
An order (through the named query) and a limit (through a hibernate setter) are also applied to the query, by order by `send_at` and limiting to 1 we are asking postgres to use both the `send_at` and `delivery_status` index at the same time which results in no index being used -- if we wanted to include this ordering we would need to have a composite index between these two columns.
However it doesn't …
> PP-10466 Fix webhook delivery queue next to send query

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
As part of protective monitoring, there is an alert to compare webhooks and webhooks-egress target domains. Currently the alert's search on the webhooks microservice logs is searching for "Sending webhook message". However this isn't correct as the presence of this log doesn't indicate webhooks microservice actually did call out to the target url. This is because at the point of this log, the target webhook url may be inactive, not on the allow list or failed because of some HTTP failure (e.g. socket timeout, interrupted exception). The splunk alert should search where the log has "Sending webhook message finished" and "to_state" is "SUCCESSFUL".
This commit adds the "domain" field to where "Sending webhook message finished" is logged so splunk can extract the log properly.
> PP-10631: Specify URL when logging 'Sending webhook message finished'

- Dockerfile
- m1/arm64.Dockerfile
Upgrade image to jdk 17.0.6 for the [amd](https://hub.docker.com/layers/library/eclipse-temurin/17-jre-alpine/images/sha256-2b33ef284e6dc43a61903cef6d36dbce13414a9e5444e2c96cdd5e35123f9903?context=explore) and [arm](https://hub.docker.com/layers/library/eclipse-temurin/17-jre/images/sha256-0563afe1aa8e2bfbf68c8ef633d67839321b8bd0a8d163f0dff2dfedef04af29?context=explore) architectures
See this [adr](https://github.com/alphagov/pay-architecture/blob/main/adr/024-java-base-image-pinning-strategy.md) on why we only specify the major version.
> PP-10717: Upgrade Docker Java image to 17.0.6

- src/main/resources/migrations/0012_alter_table_webhook_messages_add_last_delivery_status.sql
Add a column to webhook messages to allow for simple filtering of messages by status in the admin tool. This column will line up with the existing status represented on delivery queue entries and should eventually be used to filter and display the delivery status for a given message.
> PP-10543 Add last delivery status to webhook messages

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/DeliveryStatus.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueDao.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueEntity.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookDeliveryQueueResponse.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/WebhookDeliveryQueueIT.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueDaoTest.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempterTest.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessagePollingServiceTest.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageIT.java
- src/test/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDaoTest.java
Depends on https://github.com/alphagov/pay-webhooks/pull/677
Extract delivery status to be shared outside of the delivery queue class.
Ensure that any changes that are made to the enum representing possible
message delivery statuses are valid according to database constraints.
Do this by spinning up the database and running all of the enum values
against webhook message entries.
> PP-10543 Validate delivery status enumerations against database schema

- openapi/webhooks_spec.yaml
- src/main/java/uk/gov/pay/webhooks/message/dao/entity/WebhookMessageEntity.java
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookMessageResponse.java
- src/test/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDaoTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
Add entity mappings for `last_delivery_status` to serialise this from
the db.
Cover reading/ writing at the DAO level and jackson serialisation at the
resource level.
Update the open api spec to reflect the new resource attribute.
> PP-10543 Map last delivery status on webhook message

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/dao/WebhookDeliveryQueueEntity.java
- src/main/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDao.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
- src/test/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDaoTest.java
Instead of manually mapping between a string taken from the database, use the enumerated javax annotation to do this for us.
> BAU Favour enums and javax persistence (delivery queue)

- src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java
- src/test/java/uk/gov/pay/webhooks/util/SNSToSQSEventFixture.java
- src/test/resources/sns-to-sqs-event.json
When an SQS message is processed by webhooks the message was initially fanned out from SNS. The shape and properties of this message are largely static (as we're currenlty only dealing with card events) with a variable `"Message"` parameter which includes the original event body.
Clean up existing tests by abstracting out the SNS schema details into a fixture that allows specifying a simple map for the event body (the fixture builder will deal with serialisation, JSON in JSON etc.).
This should let us use this fixture in other unit/ integration tests without duplicated schema.
> PP-10543 Abstract SQS (SNS) events fixture

- pom.xml
- src/test/java/uk/gov/pay/extension/AppWithPostgresAndSqsExtension.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/WebhookDeliveryQueueIT.java
- src/test/java/uk/gov/pay/webhooks/ledger/LedgerStub.java
- src/test/java/uk/gov/pay/webhooks/ledger/TransactionFromLedgerFixture.java
- src/test/java/uk/gov/pay/webhooks/util/DatabaseTestHelper.java
Add happy path coverage for a webhook message being emitted given an
event polled from the event stream.
This PR adds wiremock for stubbing calls to external services (Ledger
and the dependant webhook callback URL).
This test covers the core components running on the webhooks service:
- an event is polled from SQS
- a webhook message is recorded for delivery
- transaction details for the webhook body are fetched from ledger
- a delivery attempt is made to the webhooks callback url for the
webhook message
> PP-10543 Happy path integration test for sending a webhook message 

- src/test/resources/config/test-config.yaml
Integration tests that verify behaviour with SQS can [now fail](https://github.com/alphagov/pay-webhooks/actions/runs/4416797500). This especially happens where a test is [asserting that messages do or don't exist on a queue](https://github.com/alphagov/pay-webhooks/blob/2afe249fa1eff482466dd7d8f5f7e211783888fd/src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java#L86).
Set the maximum timeout for fetching a batch of messages on tests to 1 second. 
The SQS client works by long polling the server and holding the HTTP connection open for a configured amount of time, if any messages become available within that timeframe the connection will be responded to and closed. By asking for a connection open for 20 seconds, the connection will continue to be fulfilled with valid messages that are …
> BAU Fix sequential SQS integration tests

- .github/dependabot.yml
Dependabot wants to bump to v20, we want to stay on the LTS v17.
> BAU: Pin Java base image to v17

- openapi/webhooks_spec.yaml
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookMessageSearchResponse.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
The admin tool should no longer provide a "Last" link when showing webhook messags pagination. The last link is calculated by taking the total number of webhook messages and dividing by the current page size.
Remove the total calculation when webhook messages are listed, this should avoid any costly lookups if there is any significant scale on webhook messages in the given webhook message TTL.
Depends on https://github.com/alphagov/pay-selfservice/pull/3849
> PP-10834 Remove total from webhook messages pagination

- openapi/webhooks_spec.yaml
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceTest.java
Internal tools like Toolbox internally consume this resource and might be trying to access a webhook outside of an account/ service context. The standard pattern for this on other endpoints is to require the identifier to be provided (to avoid internal code loading data by mistake) but to allow internal tools to provice the `override_account_or_service_id_restriction` flag.
Check existing resource tests pass and add a scenario for providing the flag without providing a service identifier.
> PP-10537 Add override flag to get one webhook endpoint

- src/main/resources/migrations/0013_alter_table_webhook_messages_add_index_on_resource_external_id.sql
Add a btree index to the webhook_messages table on the resource_external_id column, so it is possible to search for messages by the resource (payment/refund etc) id.
> PP-10836 Add index on resource_external_id

- src/main/resources/migrations/0014_alter_table_webhook_delivery_queue_add_on_delete_cascade.sql
In order to delete from webhook_messages, corresponding entries in webhook_delivery_queue need to be deleted. It would be more expedient to delete from webhook_delivery_queue by setting "ON DELETE CASCADE" to webhook_messages rather than deleting from both tables separately.
> PP-10835: Add "ON DELETE CASCADE" to webhook_messages

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- Update message to "Sending webhook message started" so that we can get splunk results without including "Sending webhook message finished" events when searching by a string.
- Change the time_to_send_in_millis logging argument to log the time since the `send_at` timestamp on the WebhookDeliveryQueueEntity. Before, for retries, we would log the time since the retry attempt WebhookDeliveryQueueEntity was created. It is more useful to log the time between the scheduled delivery time and when it was actually sent.
> PP-10957 Improve sending webhook log line

- src/main/java/uk/gov/pay/webhooks/app/WebhooksKeys.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessagePollingService.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessageHandler.java
- Log the service_external_id as a structured argument for lines logged as part of the background job to send webhook messages.
- Use the shared RESOURCE_EXTERNAL_ID logging key from pay-java-commons
- Initialise the MDC in a single place for processing events from the SQS event subscriber queue.
> PP-10957 Log service ID

- src/main/resources/config/config.yaml
- src/test/resources/config/test-config.yaml
The core webhook message delivery mechanism is built around the Postgres `"SELECT ... FOR UPDATE ... SKIP LOCKED"` feature. This allows a database transaction to gain an exclusive lock on an individual table row when initially reading it, the row will remain locked until the transaction is either commited or rolled back. Any other process or thread that makes the same query will get the next row that meets the query criteria, skipping the rows that are otherwise locked by running transactions.
If `SKIP LOCKED` is omitted, any operation making a `SELECT` with `FOR UPDATE` will _wait_ for any transaction with a row lock to complete _before_ fetching its own row and obtaining a similar lock.
`SKIP LOCKED` was introduced in PostgreSQL 9.5.
The webhooks service and the webhook delivery queue …
> PP-10940 Fix webhooks next to send logic (across processes)

- openapi/webhooks_spec.yaml
- src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/CreateWebhookRequest.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResponse.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookListIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookSigningKeyIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookUpdateIT.java
Depends on https://github.com/alphagov/pay-webhooks/pull/812
Add gateway account id to the webhooks entity to reflect the column
added to the database table.
Include on the resource model and require when creating a new webhook.
This field will be used to lookup webhooks and webhook data (message,
attempts, etc.) as a separate PR to allow the data to be appropriately
backfilled in environments before being relied on.
> PP-11019 Serealise gateway account id on webhooks

- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessage.java
- src/main/java/uk/gov/pay/webhooks/queue/EventMessageDto.java
- src/main/java/uk/gov/pay/webhooks/queue/InternalEvent.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/WebhookDao.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/WebhookDeliveryQueueIT.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageServiceTest.java
- src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java
- src/test/java/uk/gov/pay/webhooks/util/DatabaseTestHelper.java
- src/test/java/uk/gov/pay/webhooks/webhook/WebhookServiceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/dao/WebhookDaoTest.java
Gateway account IDs were added in https://github.com/alphagov/pay-webhooks/pull/812 and https://github.com/alphagov/pay-webhooks/pull/813.
They should also [be available on the payment events schema](https://github.com/alphagov/pay-connector/pull/4525).
Until the data model across Pay shifts to being service-centric, use the gateway account ID to determine if there are any webhooks subscribed for a given event (this will allow multiple test card payment accounts to be associated with a single service without causing any issues in the webhooks mechanism or reporting on webhooks data, for the time being).
> PP-11027 Lookup relevant webhook subscriptions by gateway account ID

- openapi/webhooks_spec.yaml
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/WebhookDao.java
- src/main/java/uk/gov/pay/webhooks/webhook/dao/entity/WebhookEntity.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookResource.java
- src/test/java/uk/gov/pay/webhooks/webhook/dao/WebhookDaoTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookListIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookSigningKeyIT.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookUpdateIT.java
Depends on https://github.com/alphagov/pay-webhooks/pull/820.
Until the data model across Pay shifts to being service-centric, use the
gateway account ID to allow consumers to fetch webhooks data
(this will allow multiple test card payment accounts to be
associated with a single service without causing any issues in the
webhooks mechanism or reporting on webhooks data, for the time being).
> PP-11027 Require and use gateway account ID to fetch webhooks data

- src/main/java/uk/gov/pay/webhooks/app/InternalRestClientConfig.java
- src/main/java/uk/gov/pay/webhooks/app/InternalRestClientFactory.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksConfig.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/ledger/LedgerService.java
- src/main/resources/config/config.yaml
- src/test/java/uk/gov/pay/webhooks/app/InternalRestClientFactoryTest.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/WebhookDeliveryQueueIT.java
- src/test/java/uk/gov/pay/webhooks/ledger/LedgerServiceTest.java
- src/test/java/uk/gov/pay/webhooks/ledger/pact/LedgerServiceConsumerTest.java
- src/test/resources/config/test-config.yaml
* Switch from using `java.net.http.HttpClient` to using `javax.ws.rs.client.Client`
* This lets us add a logging filter to the client - this could not be done when we were using `HttpClient`
* It also brings the project into line with how other Pay projects perform http requests
* Update tests - the new `Client` deals with deserialising body content automatically, so our implementation code is now doing less and the scope of some unit tests is thus diminished
I'm afraid I didn't get time actually test this, beyond running the automated tests.  It needs to be tested running locally (to verify that requests do get logged), and will also need testing after being merged to production, to verify that X-Request-Ids are correctly written to the logs (which can't be reproduced when testing …
> PP-10957: Use logging filter

- src/main/java/uk/gov/pay/webhooks/ledger/model/LedgerTransaction.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageService.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/WebhookDeliveryQueueIT.java
- src/test/java/uk/gov/pay/webhooks/util/DatabaseTestHelper.java
Currently webhooks only supports sending events that relate to payments. Early thinking on how to populate the resource on a webhook message decided to format the resource according to the event type, however this won't always work (in this case we want to send the payment that has been refunded, rather than the refund).
This removes that early logic but leaves the tools in place in case we need to allow services to subscribe to different types of resources in the future (refunds, disputes, agreemenets, etc.)
> PP-9850 Fix serialising child events

- src/main/java/uk/gov/pay/webhooks/message/EventMapper.java
A user has observed that payments that expire without any interaction don't receive the webhook message for "Payment expired".
It looks like the event stream differentiates between payments that are expired and require cancelling (have already authorised the payment with the gateway) and payments that are able to be immediately expired without any action.
Include the default expired event as part of the "Payment expired" subscription to allow services to be updated when this default case occurs.
> ZD-5392584 Include default payment expired event

- src/test/java/uk/gov/pay/rule/SqsTestDocker.java
v1.4.3 ([released today](https://github.com/softwaremill/elasticmq/releases)) has been failing to start during the integration tests (on this app and on connector).
> BAU: Pin to elasticmq v1.4.2

- src/main/resources/config/config.yaml
Temporarily allow webhook callback URLs hosted on the domain s118-prod-bsr-acs-common-fa.azurewebsites.net (or its subdomains) to be configured. This domain will be used temporarily by the HSE Building Safety Regulator before they switch to a .gov.uk domain, which will be in about two weeks.
> ZD-5451010 Temporarily allow custom HSE Azure domain

- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
If the request timed out, the request was still attempted. If the request was attempted, the domain is logged in the egress logs. Currently, if the reqest is timed out, the domain isn't logged in the application logs, which leads to a mismatch between the domains logged in the webhook application logs and egress logs. This causes the "Compare webhooks and webhooks-egress target domains" alert to fire unnecessarily. This commit logs the domain even if the request times out, and uses `URI.create` which does not throw a checked exception which makes the code a bit nicer.
> PP-11406: Log domain even if request timed out

- pom.xml
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksConfig.java
- src/main/resources/config/config.yaml
- src/test/resources/config/test-config.yaml
1. Remove graphite metrics configuration and sending
2. Rename GRAPHITE_SENDING_PERIOD_SECONDS to METRICS_COLLECTION_PERIOD_SECONDS, and set it to the appropriate value.
Check build passes and explicitly wait for the e2e tests to pass
> PP-11228: Remove graphite metrics sending and config

- build-local.sh
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
Now we don't need to build our default labels in the app (since they are now added by the sidecar) we should remove the default sample builder.
1. Remove default sample builder
2. Update local build script to account for m1 macs, and use the correct container tag
This change has already been rolled out to connector and is working well.
> PP-11154: Update initialise prometheus metrics

- pom.xml
- src/main/java/uk/gov/pay/webhooks/app/IdleConnectionMonitor.java
- src/main/java/uk/gov/pay/webhooks/app/QueueMessageReceiverConfig.java
- src/main/java/uk/gov/pay/webhooks/app/SqsConfig.java
- src/main/java/uk/gov/pay/webhooks/app/WebhookMessageSendingQueueProcessorConfig.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksApp.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksConfig.java
- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessageSendingQueueProcessor.java
- src/main/java/uk/gov/pay/webhooks/healthcheck/HealthCheckResource.java
- src/main/java/uk/gov/pay/webhooks/queue/QueueMessageReceiver.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempterTest.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/managed/WebhookMessagePollingServiceTest.java
- src/test/java/uk/gov/pay/webhooks/ledger/LedgerStub.java
- Upgrade Dropwizard to v3 latest.
- Use dropwizard-dependencies BOM, which removes the need to pull in some dependencies ourselves (this does make us use slightly older versions of Liquibase and Mockito but the newer contain no security fixes and we’ve used the older ones before so this should be fine.
- Dropwizard uses Jetty 10, which conflicts with WireMock, which requires Jetty 9. Fortunately, WireMock has a standalone version that includes all its dependencies. Unfortunately, the standalone version will not use our Jackson configuration, so we need to change to the way we generate some JSON for tests.
- Add JUnit Vintage so that the Pact tests, which use JUnit 4, run.
with @alexbishop1
> PP-11652 upgrade dropwizard to version 3

- .github/dependabot.yml
- pom.xml
- Use Testcontainers BOM
- Tell Dependabot not to try to upgrade us to Guice 7.0.0, which migrates from Java EE to Jakarta EE and is never going to be a just-merge-it upgrade
> BAU — Small tweaks to POM and Dependabot config

- .github/dependabot.yml
Tell Dependabot to ignore Guice 6.x and Dropwizard Sentry 4.x because neither of these are going to be just-merge-the-Dependabot-PR upgrades:
- Guice 6.x requires compatibility work on our side while Guice 7.x only works with Jakarta EE and not Java EE
- We essentially forked Dropwizard Sentry because it did not support Dropwizard 3.x — there is now a Dropwizard Sentry 4.x, which supports Dropwizard 4.x (and maybe Dropwizard 3.x), but we’d need to do work to go back to using an unmodified version
Also add comments explaining why we’re ignoring upgrades for certain Maven dependencies.
> BAU — Tell Dependabot to ignore Guice 6 and Dropwizard Sentry 4

- .github/workflows/codeql.yml
Unlike our other Java repositories, we need custom config file to pick up the Java 17 adopt env
[See a successful workflow run here](https://github.com/alphagov/pay-webhooks/actions/runs/7933335885/job/21661864236) (NB scan results are **not** shown here)
> PP-12211: CodeQL config for Webhooks

- .github/workflows/codeql.yml
The CodeQL scans should now only run on changes to Java code (so e.g. it won't run on Docker image Dependabot PRs).
Also removes post-merge workflow trigger - this is probably overkill given we also have weekly scheduled scans.
> PP-12211: Run CodeQL on Java code only

- pom.xml
- src/test/java/uk/gov/pay/webhooks/ledger/pact/LedgerServiceConsumerTest.java
`pay-java-commons` was upgraded to Java 21. Some of the imports needed update as they are transative dependencies.
> PP-12789 upgrade to pay-java-commons

- src/main/resources/migrations/00016_create_procedure_check_and_execute.sql
Add stored procedure check_and_execute which allows specifying SQL, the table, and expected number of rows affected. This should allow ad-hoc modifications to be done more safely since it will automatically error if the number of rows affected wasn't exactly what you had intended
This is based on the prior art in https://github.com/alphagov/pay-connector/pull/5451/ and the RFC https://github.com/alphagov/pay-architecture/discussions/147
The formatting of the liquibase migrations meant I had to slightly edit the sql and replace the $$ quoted multi line string with single `'` quotes (and change all single quotes inside it to 2 x single quotes `''` (not double quotes)
- Locally run up pay local with this branch of webhooks `pay local up --cluster card --local webhooks`
- Once it's running …
> PP-13026: Add stored procedure to allow safer manual sql execution

- src/main/resources/config/config.yaml
- src/test/resources/config/test-config.yaml
MOD is not under guv.uk, they have their own domain.
> ZD-5946282 add cadets.mod.uk to allow domain list

- openapi/webhooks_spec.yaml
- src/main/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDao.java
- src/main/java/uk/gov/pay/webhooks/message/resource/WebhookMessageSearchResponse.java
- src/main/java/uk/gov/pay/webhooks/webhook/WebhookService.java
- src/main/java/uk/gov/pay/webhooks/webhook/resource/WebhookMessageSearchParams.java
- src/test/java/uk/gov/pay/webhooks/message/dao/WebhookMessageDaoTest.java
- src/test/java/uk/gov/pay/webhooks/webhook/resource/WebhookResourceIT.java
In order to implement better pagination of webhook events in selfservice, we need the total message count to be returned in response to a list webhook messages request.
- Add the total number of messages to the response
- Add unit tests for getting the total message count by webhook id and by status
- Update integration tests
> PP-13521 Add total to webhook messages response

- pom.xml
- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/healthcheck/SQSHealthCheck.java
- src/main/java/uk/gov/pay/webhooks/queue/sqs/QueueMessage.java
- src/main/java/uk/gov/pay/webhooks/queue/sqs/SqsQueueService.java
- src/test/java/uk/gov/pay/extension/AppWithPostgresAndSqsExtension.java
- src/test/java/uk/gov/pay/rule/SqsTestDocker.java
- src/test/java/uk/gov/pay/webhooks/deliveryqueue/WebhookDeliveryQueueIT.java
- src/test/java/uk/gov/pay/webhooks/healthcheck/HealthCheckResourceIT.java
- src/test/java/uk/gov/pay/webhooks/ledger/TransactionFromLedgerFixture.java
- src/test/java/uk/gov/pay/webhooks/queue/EventQueueIT.java
- src/test/java/uk/gov/pay/webhooks/util/SNSToSQSEventFixture.java
The AWS SDK for Java 1.x is in maintenance mode, effective July 31, 2024.
The AWS SDK for Java 1.x will no longer receive updates for new or existing services.
We need to upgrade pay-ledger to use the AWS SDK version 2 for SQS operations. This will involve updating dependencies, refactoring code to accommodate changes in the SDK, and ensuring the new SDK's methods and patterns are followed.
> PP-13648 Upgrade java aws sdk to version 2

- src/main/java/uk/gov/pay/webhooks/app/WebhooksModule.java
- src/main/java/uk/gov/pay/webhooks/message/HttpPostFactory.java
- src/main/java/uk/gov/pay/webhooks/message/WebhookMessageSender.java
- src/test/java/uk/gov/pay/webhooks/message/WebhookMessageSenderTest.java
Send webhook messages encoded as UTF-8. We used to do this but when we switched to the Apache HttpClient (which uses different defaults) in commit 65aaa6c00b6b623411b1b40236982ac6261ee12b we unintentionally started using ISO-8859-1.
Worse, the signature generation code continued to calculate based on UTF-8 bytes so in some cases our signatures did not actually match the bytes sent!
> PP-14206 Send webhook messages encoded as UTF-8

- src/main/java/uk/gov/pay/webhooks/app/WebhooksKeys.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
Updating the logging wording to clearly denote the time between when the webhook  was scheduled to happen and when it actually happened. The current wording:
`time_to_send_in_millis`
is unclear and there will be another PR to remove it after manually checking this change is searchable in Splunk and changes have been made in the `cyber-security-splunk-apps` repo.
> PP-14198 Change logging message to reflect the attempt number

- src/main/java/uk/gov/pay/webhooks/app/WebhooksKeys.java
- src/main/java/uk/gov/pay/webhooks/deliveryqueue/managed/SendAttempter.java
Removing the `WEBHOOK_MESSAGE_TIME_TO_SEND_IN_MILLIS` variable as it's been replaced by the more clearly named `WEBHOOK_MESSAGE_DELAY_BETWEEN_ATTEMPT_SCHEDULED_SEND_AT_TIME_AND_NOW`.
> PP-14198 remove message time_to_send_in_millis
